# Generated by Django 3.2.5 on 2021-12-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usergroup'),
        ),
    ]
