# Generated by Django 3.2.5 on 2021-12-11 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressdetail',
            options={},
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educationlevel'),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='secured_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='total_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='user_address', to='core.AddressDetail'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_groups',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('SC', 'ST'), ('OBC', 'OBC'), ('SEBC', 'SEBC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_details',
            field=models.ManyToManyField(related_name='user_addresses', to='core.EducationDetail'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('HINDU', 'HINDU'), ('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM'), ('SIKH', 'SIKH'), ('JAIN', 'JAIN'), ('PARSI', 'PARSI'), ('BUDDHIST', 'BUDDHIST'), ('JEWISH', 'JEWISH'), ('JEWSIH', 'JEWISH')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
