# Generated by Django 3.2.5 on 2021-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211211_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('year_of_esht', models.CharField(max_length=4)),
                ('num_of_seats', models.IntegerField()),
                ('is_ugc_accre', models.BooleanField(default=False)),
                ('is_nb_accre', models.BooleanField(default=False)),
                ('departments', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='courses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_academic',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='year_of_esht',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='programme',
            field=models.ManyToManyField(related_name='branch_programme', to='core.Program'),
        ),
    ]
