# Generated by Django 3.2.5 on 2021-11-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211125_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationDetails',
            new_name='EducationDetail',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branchs'},
        ),
        migrations.AlterModelOptions(
            name='educationdetail',
            options={'verbose_name_plural': 'EducationDetails'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name_plural': 'EducationLevels'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name_plural': 'UserGroups'},
        ),
    ]
