# Generated by Django 3.2.5 on 2021-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211125_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Address_Detail',
        ),
        migrations.AlterModelOptions(
            name='address_detail',
            options={'verbose_name_plural': 'Address_Details'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
