# Generated by Django 3.2.5 on 2021-12-17 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211217_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetail',
            name='address_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='police_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_eucationdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='user_addressdetails', to='core.AddressDetail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_details',
            field=models.ManyToManyField(related_name='user_educationdetails', to='core.EducationDetail'),
        ),
    ]
