# Generated by Django 3.2.5 on 2021-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211217_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('year_of_esht', models.CharField(max_length=4, null=True)),
                ('is_academic', models.BooleanField(default=False)),
                ('courses', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.RemoveField(
            model_name='branch',
            name='programme',
        ),
    ]
