# Generated by Django 3.2.5 on 2021-12-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211127_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address_Detail',
            new_name='AddressDetail',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='student_default.jpg', upload_to='StudentPics'),
        ),
    ]
