# Generated by Django 3.2.5 on 2021-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211217_1803'),
        ('core', '0007_auto_20211217_1803'),
        ('student', '0003_auto_20211217_1803'),
        ('faculty', '0008_auto_20211217_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='department',
            name='programme',
            field=models.ManyToManyField(related_name='branch_programme', to='core.Program'),
        ),
    ]
