# Generated by Django 3.2.5 on 2021-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20211223_1314'),
        ('core', '0008_alter_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='Dept_courses', to='academics.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='programme',
            field=models.ManyToManyField(blank=True, related_name='branch_programme', to='academics.Program'),
        ),
    ]
