# Generated by Django 3.2.5 on 2021-12-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211225_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
