# Generated by Django 3.2.5 on 2021-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20211222_2114'),
        ('academics', '0001_initial'),
        ('core', '0009_alter_department_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(max_length=100, null=True, to='academics.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='programme',
            field=models.ManyToManyField(related_name='branch_programme', to='academics.Program'),
        ),
    ]
