# Generated by Django 3.2.5 on 2022-01-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='core.user'),
            preserve_default=False,
        ),
    ]
