# Generated by Django 3.2.5 on 2022-01-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usergroup_site_url'),
        ('core', '0015_alter_addressdetail_address_type'),
    ]

    operations = [
    ]
