# Generated by Django 3.2.5 on 2022-01-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20220102_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='department_default.jpg', null=True, upload_to='DepartmentPics'),
        ),
    ]
