# Generated by Django 3.2.5 on 2022-01-22 13:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220121_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='student_default.jpg', null=True, upload_to=core.models.userFile),
        ),
    ]
