# Generated by Django 3.2.5 on 2022-01-22 14:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default='department_default.jpg', null=True, upload_to=core.models.departmentFile),
        ),
    ]
