# Generated by Django 3.2.5 on 2022-01-24 02:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='email', unique=True),
            preserve_default=False,
        ),
    ]
