# Generated by Django 3.2.5 on 2022-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_course_course_code'),
        ('core', '0023_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='Dept_courses', to='academics.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='programme',
            field=models.ManyToManyField(blank=True, related_name='branch_programme', to='academics.Program'),
        ),
    ]
