# Generated by Django 3.2.5 on 2021-12-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod_tenure',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='hod_tenure',
            old_name='emp',
            new_name='employee',
        ),
    ]
