# Generated by Django 3.2.5 on 2021-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='faculty',
            name='work_email_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='work_phone_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
