# Generated by Django 3.2.5 on 2021-12-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211223_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='faculty_publications', to='faculty.Publication'),
        ),
    ]
