# Generated by Django 3.2.5 on 2021-12-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211211_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='empoyee',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='work_email_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='work_phone_number',
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='teach_experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('fclty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='publications',
            field=models.ManyToManyField(related_name='faculty_publications', to='faculty.Publication'),
        ),
    ]
