# Generated by Django 3.2.5 on 2021-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211124_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hod_tenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='EducationDetails',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='date_of_joining',
        ),
    ]
