# Generated by Django 3.2.5 on 2021-12-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_quaification_faculty_qualification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='designation',
        ),
    ]
