# Generated by Django 3.2.5 on 2021-12-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20211214_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='fclty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
    ]
