# Generated by Django 3.2.5 on 2021-12-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_publication_fclty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='fclty',
        ),
    ]
