# Generated by Django 3.2.5 on 2021-12-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211217_1803'),
        ('faculty', '0007_remove_publication_fclty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod_tenure',
            name='branch',
        ),
        migrations.AddField(
            model_name='hod_tenure',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
