# Generated by Django 3.2.5 on 2022-01-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_publication_faculty'),
        ('faculty', '0007_alter_faculty_user'),
    ]

    operations = [
    ]
