# Generated by Django 3.2.5 on 2022-01-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_merge_20220115_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_publication', to='faculty.faculty'),
        ),
    ]
