# Generated by Django 3.2.5 on 2021-12-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_descr', models.CharField(max_length=100, null=True)),
                ('curr_posn', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_department', to='core.department')),
                ('desg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('emp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
