# Generated by Django 3.2.5 on 2021-12-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='curr_posn',
            new_name='current_position',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='desg',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='emp',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='job_descr',
            new_name='job_description',
        ),
    ]
