# Generated by Django 3.2.5 on 2022-01-24 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_alter_employee_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0004_staff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='dept',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='staff',
            name='current_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.designation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_detail', to='core.user'),
            preserve_default=False,
        ),
    ]
