# Generated by Django 3.2.5 on 2022-01-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_alter_employee_job_type'),
        ('staff', '0005_auto_20220124_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_Designation_detail', to='employee.designation'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_employee_detail', to='employee.employee'),
        ),
    ]
