# Generated by Django 3.2.5 on 2021-12-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pay', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('work_phone_number', models.CharField(max_length=12, null=True)),
                ('work_email_id', models.EmailField(max_length=20, null=True)),
                ('pan_number', models.CharField(max_length=10, null=True)),
                ('job_type', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation', to='employee.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_granted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('leave_address', models.CharField(max_length=50, null=True)),
                ('leave_phone_number', models.CharField(max_length=12, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_leave', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Leaves',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_role', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('previous_posn', models.CharField(max_length=50, null=True)),
                ('current_posn', models.CharField(max_length=50, null=True)),
                ('prev_salary', models.IntegerField(null=True)),
                ('curr_salary', models.IntegerField(null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_prmtion', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_type', to='employee.leave')),
            ],
            options={
                'verbose_name_plural': 'LeaveTypes',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('organisation_name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_detail', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='experiences',
            field=models.ManyToManyField(related_name='employe_experience', to='employee.Experience'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leaves',
            field=models.ManyToManyField(related_name='employee_leave', to='employee.Leave'),
        ),
        migrations.AddField(
            model_name='employee',
            name='promotions',
            field=models.ManyToManyField(related_name='employee_promotion', to='employee.Promotion'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Account_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.BigIntegerField(null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('branch_name', models.CharField(max_length=50, null=True)),
                ('ifsc', models.CharField(max_length=50, null=True)),
                ('cif', models.CharField(max_length=50, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_account', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Account_Details',
            },
        ),
    ]
