# Generated by Django 3.2.5 on 2021-12-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_detail',
            old_name='emp',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='desg',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='emp',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='emp',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='current_posn',
            new_name='current_position',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='curr_salary',
            new_name='current_salary',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='previous_posn',
            new_name='previous_position',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='prev_salary',
            new_name='previous_salary',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='emp',
            new_name='employee',
        ),
    ]
