# Generated by Django 3.2.5 on 2021-12-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211212_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Types',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experiences',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email_id',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('previous_posn', models.CharField(max_length=50, null=True)),
                ('current_posn', models.CharField(max_length=50, null=True)),
                ('prev_salary', models.IntegerField(null=True)),
                ('curr_salary', models.IntegerField(null=True)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_granted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('leave_address', models.CharField(max_length=50, null=True)),
                ('leave_phone_number', models.CharField(max_length=12, null=True)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.leavetype')),
            ],
            options={
                'verbose_name_plural': 'Leaves',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='leaves',
            field=models.ManyToManyField(related_name='employee_leave', to='employee.Leave'),
        ),
        migrations.AddField(
            model_name='employee',
            name='promotions',
            field=models.ManyToManyField(related_name='employee_promotion', to='employee.Promotion'),
        ),
    ]
