# Generated by Django 3.2.5 on 2021-12-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
