# Generated by Django 3.2.5 on 2021-12-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20211214_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name_plural': 'LeaveTypes'},
        ),
    ]
