# Generated by Django 3.2.5 on 2021-12-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_designation_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=50, null=True),
        ),
    ]
