# Generated by Django 3.2.5 on 2021-12-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_leavetype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pay', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.leave'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='desg',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.designation'),
        ),
    ]
