# Generated by Django 3.2.5 on 2021-12-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_account_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_account', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation', to='employee.designation'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experiences',
        ),
        migrations.AlterField(
            model_name='leave',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_leave', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_type', to='employee.leave'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_prmtion', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('organisation_name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_detail', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='experiences',
            field=models.ManyToManyField(related_name='employe_experience', to='employee.Experience'),
        ),
    ]
