# Generated by Django 3.2.5 on 2022-02-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0035_auto_20220201_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=50, null=True),
        ),
    ]
