# Generated by Django 3.2.5 on 2022-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_auto_20220204_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=50, null=True),
        ),
    ]
