# Generated by Django 3.2.5 on 2022-02-05 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0037_alter_employee_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_halfday', models.BooleanField(default=False)),
                ('is_granted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('leave_address', models.CharField(max_length=50, null=True)),
                ('leave_phone_number', models.CharField(max_length=12, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaves',
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_days', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'LeaveRecords',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leaves',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leave_Record_Employee_Details', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='leave_applications',
            field=models.ManyToManyField(related_name='Leave_Record_Applications', to='employee.LeaveApplication'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leave_Record_Type', to='employee.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_leave', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_type', to='employee.leavetype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_records',
            field=models.ManyToManyField(related_name='Employee_leave_record', to='employee.LeaveRecord'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leaves_application',
            field=models.ManyToManyField(related_name='employee_leave', to='employee.LeaveApplication'),
        ),
    ]
