# Generated by Django 3.2.5 on 2021-12-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jee_roll', models.CharField(max_length=100, null=True)),
                ('jee_rank', models.CharField(max_length=100, null=True)),
                ('programme', models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('B.Tech. DD.', 'B.Tech. + M.Tech.'), ('M.Tech.', 'M.Tech.'), ('B.Arch.', 'B.Arch.'), ('MCA', 'MCA'), ('M.Sc.', 'M.Sc'), ('Int.M.Sc', 'Int.M.Sc'), ('M.Phil.', 'M.Phil.'), ('Ph.D.', 'Ph.D')], max_length=50, null=True)),
                ('entrance_exam', models.CharField(choices=[('JEE-MAIN', 'JEE-MAIN'), ('OJEE', 'OJEE')], default='JEE-MAIN', max_length=50)),
                ('is_Tfw', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('REGULAR', 'REGULAR'), ('SELF-SUSTAINING', 'SELF-SUSTAINING')], default='REGULAR', max_length=50)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_defence', models.BooleanField(default=False)),
                ('is_green_card', models.BooleanField(default=False)),
                ('parents_mobile', models.CharField(max_length=12, null=True)),
                ('parents_email', models.EmailField(max_length=254, null=True)),
                ('application_time', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('course', models.ManyToManyField(related_name='student_applicant_courses', to='academics.Program')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BigIntegerField(null=True, unique=True)),
                ('verification_time', models.DateTimeField(null=True)),
                ('entrance_exam', models.CharField(choices=[('JEE-MAIN', 'JEE-MAIN'), ('OJEE', 'OJEE')], default='JEE-MAIN', max_length=50)),
                ('academic_session', models.CharField(max_length=5, null=True)),
                ('is_tfw', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('REGULAR', 'REGULAR'), ('SELF-SUSTAINING', 'SELF-SUSTAINING')], default='REGULAR', max_length=50)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_defence', models.BooleanField(default=False)),
                ('is_green_card', models.BooleanField(default=False)),
                ('parent_email', models.EmailField(max_length=254, null=True)),
                ('parent_mobile', models.CharField(max_length=12, null=True)),
                ('jee_roll', models.CharField(max_length=50, null=True)),
                ('jee_rank', models.CharField(max_length=50, null=True)),
                ('entry_gate', models.CharField(max_length=50, null=True)),
                ('program', models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('B.Tech. DD.', 'B.Tech. + M.Tech.'), ('M.Tech.', 'M.Tech.'), ('B.Arch.', 'B.Arch.'), ('MCA', 'MCA'), ('M.Sc.', 'M.Sc'), ('Int.M.Sc', 'Int.M.Sc'), ('M.Phil.', 'M.Phil.'), ('Ph.D.', 'Ph.D')], max_length=50, null=True)),
                ('application_time', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student_application')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('registration',)},
            },
        ),
    ]
