# Generated by Django 3.2.5 on 2021-12-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student_application',
            old_name='dept',
            new_name='department',
        ),
    ]
