# Generated by Django 3.2.5 on 2021-12-28 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211223_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_application',
            name='application_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 28, 14, 32, 32, 839579, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
