# Generated by Django 3.2.5 on 2021-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211124_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='twelve_yop',
        ),
    ]
