# Generated by Django 3.2.5 on 2021-11-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20211127_1449'),
        ('student', '0003_remove_student_twelve_yop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='jee_rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='jee_roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='application_time',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='verified_by',
            field=models.OneToOneField(default='Admin', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jee_roll', models.CharField(max_length=100, null=True)),
                ('jee_rank', models.CharField(max_length=100, null=True)),
                ('programme', models.CharField(choices=[('B.Tech.', 'B.Tech.')], max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
