# Generated by Django 3.2.5 on 2021-12-18 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20211217_1803'),
        ('student', '0003_auto_20211217_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_session',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student_application'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_exam',
            field=models.CharField(choices=[('JEE-MAIN', 'JEE-MAIN'), ('OJEE', 'OJEE')], default='JEE-MAIN', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_gate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_defence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_green_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_tfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='jee_rank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='jee_roll',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mode',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('SELF-SUSTAINING', 'SELF-SUSTAINING')], default='REGULAR', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('B.Tech. DD.', 'B.Tech. + M.Tech.'), ('M.Tech.', 'M.Tech.'), ('B.Arch.', 'B.Arch.'), ('MCA', 'MCA'), ('M.Sc.', 'M.Sc'), ('Int.M.Sc', 'Int.M.Sc'), ('M.Phil.', 'M.Phil.'), ('Ph.D.', 'Ph.D')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_application',
            name='course',
            field=models.ManyToManyField(related_name='student_applicant_courses', to='core.Program'),
        ),
        migrations.AddField(
            model_name='student_application',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='verification_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='is_Tfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='is_defence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='is_green_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='programme',
            field=models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('B.Tech. DD.', 'B.Tech. + M.Tech.'), ('M.Tech.', 'M.Tech.'), ('B.Arch.', 'B.Arch.'), ('MCA', 'MCA'), ('M.Sc.', 'M.Sc'), ('Int.M.Sc', 'Int.M.Sc'), ('M.Phil.', 'M.Phil.'), ('Ph.D.', 'Ph.D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('registration',)},
        ),
    ]
