# Generated by Django 3.2.5 on 2021-12-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_application_user'),
        ('student', '0003_auto_20211217_1803'),
    ]

    operations = [
    ]
