# Generated by Django 3.2.5 on 2021-12-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20211228_2015'),
        ('student', '0003_alter_student_application_application_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_application',
            name='course',
        ),
        migrations.AddField(
            model_name='student_application',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_applicant_courses', to='academics.program'),
        ),
    ]
