# Generated by Django 3.2.5 on 2021-12-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_merge_20211217_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_application',
            old_name='dept',
            new_name='department',
        ),
    ]
