# Generated by Django 3.2.5 on 2021-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
