# Generated by Django 3.2.5 on 2021-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211218_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_session',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
