# Generated by Django 3.2.5 on 2021-12-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_academic_session'),
        ('student', '0005_rename_dept_student_application_department'),
    ]

    operations = [
    ]
