# Generated by Django 3.2.5 on 2021-12-30 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_alter_student_application_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='student_application',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='status',
            field=models.CharField(choices=[('UNDER VERIFICATION', 'UNDER VERIFICATION'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='UNDER VERIFICATION', max_length=50),
        ),
    ]
