# Generated by Django 3.2.5 on 2021-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_application_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
