# Generated by Django 3.2.5 on 2021-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_merge_20211220_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_application',
            old_name='department',
            new_name='dept',
        ),
    ]
