# Generated by Django 3.2.5 on 2021-12-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211230_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_application',
            old_name='status',
            new_name='status_application',
        ),
    ]
