# Generated by Django 3.2.5 on 2021-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_application_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='application_time',
        ),
        migrations.AddField(
            model_name='student',
            name='verification_time',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
