# Generated by Django 3.2.5 on 2021-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_status_student_application_status_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_application',
            name='status_application',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
