# Generated by Django 3.2.5 on 2021-12-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_merge_20211220_2204'),
        ('student', '0007_rename_department_student_application_dept'),
    ]

    operations = [
    ]
