# Generated by Django 3.2.5 on 2021-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_verification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='verification_time',
            field=models.DateTimeField(),
        ),
    ]
