# Generated by Django 3.2.5 on 2022-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_application_status_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_application',
            name='academic_session',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_application',
            name='entry_gate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
