# Generated by Django 3.2.5 on 2022-01-19 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_auto_20220119_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_application',
            name='registration',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_application',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verifier_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
