# Generated by Django 3.2.5 on 2022-01-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_application_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='gate_entry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_gate',
        ),
    ]
