# Generated by Django 3.2.5 on 2022-01-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20220119_2322'),
        ('student', '0012_auto_20220120_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_application',
            name='programme',
        ),
        migrations.AddField(
            model_name='student_application',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_applicant_programs', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
    ]
