# Generated by Django 3.2.5 on 2021-12-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
        ('student', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterrecord',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='semesterrecord',
            name='sem_course',
            field=models.ManyToManyField(related_name='sem_rec_sem_coursedetail', to='academics.SemesterCourse'),
        ),
        migrations.AddField(
            model_name='semesterrecord',
            name='student',
            field=models.ManyToManyField(related_name='sem_rec_studentdetail', to='student.Student'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semmarks_deptdetails', to='core.department'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='exam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.examination'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semmarks_fcltydetails', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='sem_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semmark_coursedetails', to='academics.semestercourse'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem_coursedetails', to='academics.course'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='daily_class_report',
            field=models.ManyToManyField(related_name='sem_course_daily_class_report', to='academics.DailyClassReport'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semcourse_fcltydetails', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='sem_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semesterrecord'),
        ),
        migrations.AddField(
            model_name='program',
            name='departments',
            field=models.ManyToManyField(related_name='program_department', to='core.Department'),
        ),
        migrations.AddField(
            model_name='examination',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_deptdetail', to='core.department'),
        ),
        migrations.AddField(
            model_name='examination',
            name='sem_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_semcoursedetails', to='academics.semestercourse'),
        ),
        migrations.AddField(
            model_name='examination',
            name='sem_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_semrecdeetails', to='academics.semesterrecord'),
        ),
        migrations.AddField(
            model_name='dailyclassreport',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clsrpt_fcltydetails', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='dailyclassreport',
            name='sem_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clsrpt_semcoursedetails', to='academics.semestercourse'),
        ),
        migrations.AddField(
            model_name='dailyclassreport',
            name='student_prsnt',
            field=models.ManyToManyField(related_name='clsrpt_Studentdetail', to='student.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_department', to='core.department'),
        ),
    ]
