# Generated by Django 3.2.5 on 2022-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20220119_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='num_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='year_of_esht',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
