# Generated by Django 3.2.5 on 2022-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20220121_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
