# Generated by Django 3.2.5 on 2022-02-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20220120_2145'),
        ('academics', '0007_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclassreport',
            name='student_present',
            field=models.ManyToManyField(related_name='daily_class_report_student', to='student.Student'),
        ),
        migrations.AddField(
            model_name='semestermarks',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_semester_marks', to='student.student'),
        ),
    ]
